#!/bin/bash
FILES=$(git diff-index --cached --name-only --diff-filter=ACMR HEAD)
ERRORS=""

for file in $FILES
do
    FILENAME=$(basename $file)
    EXTENSION=$(awk -F . '{print $NF}' <<< $FILENAME)

    case "$EXTENSION" in
        "js")
            ERROR=$(grep -Ein "console\.(dir|error|group|groupCollapsed|groupEnd|info|log|time|timeEnd|trace|warn)" $file | cut -d : -f 1)
            if [ "$ERROR" != "" ]; then
                ERRORS=${ERRORS}${ERROR}
                echo -e "\033[31mConsole statement found in\033[1m" $file "\033[0m\033[31mat line:" $(sed 's/ /, /g' <<< $ERROR) "\033[0m"
            fi
        ;;
    esac
done

if [ "$ERRORS" != "" ]; then
    echo -e "\e[31mPlease remove console statements!\e\0m"
    exit 1;
fi
